### ISSUE TITLE
在集成到layim中出现了一下问题

### ISSUE THREAD

**Issue by typ1758** [yuri2peter/win10-ui#1]
请教一下，集成过程中出现的问题：不能识别win10，

**Comment by yuri2peter** [comment]
描述太笼统了，看一下win10.js是否正常被加载，控制台调用api试试

**Comment by typ1758** [comment]
我通过
//主动加载jquery模块
layui.use(['jquery', 'layer'], function(){ 
  var $ = layui.jquery //重点处
  ,layer = layui.layer;
  
  //后面就跟你平时使用jQuery一样
 //在这里把整个win10.js放在这里了
});
在html中不能调用api，提示找不到，
请问这个问题怎么解决呢？感谢

**Comment by yuri2peter** [comment]
已解决，注意保持Win10对象在全局作用域
