### ISSUE TITLE
iframe参数问题

### ISSUE THREAD

**Issue by nwdxlgzs** [yuri2peter/win10-ui#15]
iframe参数可不可以提供类似security="restricted" sandbox="allow-scripts allow-same-origin allow-popups"的可选参数，比如访问https://wx.qq.com/和http://hgkbk.bjeea.cn/网页，会导致重定向到对应网址而不是iframe，当前demo就可以提示是否离开网站，但是，比如微信，时不时就弹出来影响体验{https://wx.qq.com/}，比如一些重定向就失效{http://hgkbk.bjeea.cn/有时候加入沙箱选项后发生这类问题}或者不加载的网址{比如谷歌（不是指被墙，就是不加载）}。能不能解决一下。src参数能不能一开始就支持file:///省得每次删http://协议。

**Comment by yuri2peter** [comment]
微信谷歌这种屏蔽了iframe没啥好办法
