### ISSUE TITLE
⚠️DMCA WARNING!

### ISSUE THREAD

**Issue by uqsme** [yuri2peter/win10-ui#18]
自主研发前

https://github.com/yuri2peter/win10-ui/blob/9ab833f21d401721765e80228f14ec0829572255/js/win10.js#L866-L870

自主研发后

https://github.com/xingyujie/flyos/blob/3f9766de9dbaaa98fd02b27d4049e69c5217397a/panel/FlyOSPanel/statics/js/win10.js#L866-L870

**Comment by AldarisX** [comment]
现在master分支还在，并没有修改

**Comment by liulihaocai** [comment]
flyos那边说您是他的熟人请问是不是真的

**Comment by liulihaocai** [comment]
flyos那边说yuri是他的熟人是不是真的

**Comment by leoleoasd** [comment]
项目用的SATA许可证，要求保留贡献者名称。建议直接给GitHub发DMCA takedown request
