### ISSUE TITLE
小小建议：已经打开的菜单再次打开时应该弹出之前打开的，而不是新打开一个tab

### ISSUE THREAD

**Issue by ht896632** [yuri2peter/win10-ui#2]
已经打开的菜单再次打开时应该弹出之前打开的，而不是新打开一个tab，作者可以考虑修改下；

**Comment by yuri2peter** [comment]
感谢你提出的建议。因为有的场景需要独立的两个，有的又不需要，我打算添加api的来让开发者自己控制，下一个1.1版本吧。

**Comment by gitlsl** [comment]
很漂亮的ui  支持一下

**Comment by gitlsl** [comment]
@yuri2peter 右边的消息最下面有1个像素没覆盖到 #win10_command_center 的 bottom 应该再减少一个像素 (调整为40)

**Comment by yuri2peter** [comment]
@gitlsl 那是一条性感的分界线
