### ISSUE TITLE
建议:拖拽的时候用虚框显示拖拽,会更流畅一些.

### ISSUE THREAD

**Issue by c5ms** [yuri2peter/win10-ui#3]
显示是整个画面直接跟随移动,
在外面包装一层虚框,拖拽只移动虚框,放下的时候移动画面,应该会更流程一些.

**Comment by yuri2peter** [comment]
是会流畅，但是观感会变差。关键问题是。。。拖拽是layer的功能，并不好修改（尽量不修改第三方的代码）
