### ISSUE TITLE
我帮你优化的一个细节

### ISSUE THREAD

**Issue by iamlk** [yuri2peter/win10-ui#6]
_startAnimate:function () {
        setInterval(function () {
            var classes_lenth=Win10._animated_classes.length;
            var animated_liveness=Win10._animated_liveness;
            if(animated_liveness===0 || classes_lenth===0 || !$("#win10-menu").hasClass('opened')){return;}
            $('#win10-menu>.blocks>.menu_group>.block').each(function () {
                if(!$(this).hasClass('onAnimate') && Math.random()<=animated_liveness){
                    var that=$(this);
                    var class_animate = Win10._animated_classes[Math.floor((Math.random()*classes_lenth))];
                     **# that.css('zIndex',999);**
                    that.addClass('onAnimate');
                    setTimeout(function () {
                        that.addClass(class_animate);
                        setTimeout(function () {
                            that.removeClass('onAnimate');
                            that.removeClass(class_animate);
                            **# that.css('zIndex',1);**
                        },3000);
                    },Math.random()*100)
                }
            })
        },100);
    },

**Comment by yuri2peter** [comment]
哎？改动的位置和效果是什么呢

**Comment by iamlk** [comment]
改动位置你搜代码就能搜到
改动的效果是开始菜单里面那些方块旋转的时候，z-index是最外层，这样不会被遮挡住，效果更真实
